### PR TITLE
Allow Playwright in Runtime module and GraalVM support

### LINKED ISSUE #68: Playwright in Quarkus Native (not for E2E testing)
I understand that Quarkus supports Playwright for E2E testing, but I want to use it for web scraping. Specifically, I want to deploy Native Quarkus which uses Playwright to scrape websites.

Is this supported by this plugin? Does it work when compiled to Native?

### PR DESCRIPTION
**Pull request by melloware**
This will allow using Playwright at Runtime for people who want to screen scrape.

- [x] Allow use at runtime for people who want to use it for screen scraping or other purposes
- [x] rename playwright to `playwright-test`
- [x] Fix #68 Native mode
- [x] Replace `System.out.println` logging with Jboss logging with Graal Substitution

NOTE: this required me to rename the artifactId for playwright to playwright-test which is a breaking change so this should be a 2.0.0 if we go forward.

image

### CODE REVIEW

**Comment by maxandersen** [comment]
sounds like good idea to me. whats the migration path? remove `-test` but keep it in import scope test?

Any reason to not also provide a artifact named `-test` that just includes the non-test one ?

**Comment by melloware** [comment]
That is a good question. You are saying I could theoretically put all the `test` stuff in the `runtime` module and poeple could choose whether or not to mark it `<scope>test</scope>` or not?

**Comment by ia3andy** [comment]
> That is a good question. You are saying I could theoretically put all the `test` stuff in the `runtime` module and poeple could choose whether or not to mark it `<scope>test</scope>` or not?

I also thought about it :) we should try

**Comment by melloware** [comment]
let me try it!

**Comment by maxandersen** [comment]
yes and no - my main question was what the migration path was (if any) and if that was to just remove "-test" then why not just have "-test" include the new runtime one and all is good...

**Comment by melloware** [comment]
Oh sorry the migration path would be if you use this now.

```xml
<dependency>
    <groupId>io.quarkiverse.playwright</groupId>
    <artifactId>quarkus-playwright</artifactId>
    <version>${playwright.version}</version>
    <scope>test</scope>
</dependency>
```

it changes to

```xml
<dependency>
    <groupId>io.quarkiverse.playwright</groupId>
    <artifactId>quarkus-playwright-test</artifactId>
    <version>${playwright.version}</version>
    <scope>test</scope>
</dependency>
```

**Comment by melloware** [comment]
OK it looks like it works!  I moved the Test code into the Runtime library and just marked `junit5` as an OPTIONAL dependency.

**Comment by ia3andy** [comment]
I think that's ok as the testing part is really small and won't be in the target user app. @aloubyansky any thoughts?

**Comment by aloubyansky** [comment]
You mean the optional dependency on the quarkus-junit5-internal?

**Comment by melloware** [comment]
Yep

```xml
 <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <optional>true</optional>
        </dependency>
```

**Comment by aloubyansky** [comment]
What specifically do you achieve with that?

**Comment by melloware** [comment]
Because we offer Unit testing classes with `@WithPlaywright` that are QuarkusTest only but also allow PlayWright to be used as a ScreenScraper.  So anyone using it as a Test library will do this...

```xml
<dependency>
    <groupId>io.quarkiverse.playwright</groupId>
    <artifactId>quarkus-playwright</artifactId>
    <version>${playwright.version}</version>
    <scope>test</scope>
</dependency>
<dependency>
     <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
       <scope>test</scope>
</dependency>
```

and anyone wanting to use it as a runtime screen scraper can do this....

```xml
<dependency>
    <groupId>io.quarkiverse.playwright</groupId>
    <artifactId>quarkus-playwright</artifactId>
    <version>${playwright.version}</version>
</dependency>
```

**Comment by aloubyansky** [comment]
Ah, not the `internal` one and the user has to still add the dependency on the `quarkus-junit5` - sure, makes sense. Thanks.

**Comment by melloware** [comment]
I was also able to Graal substitute as Playwright uses `System.out.println` for logging with Jboss logging!

**Pull request merged**
